export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ID = 'GET_USER_ID';
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_WITH_BACKUP = 'LOGOUT_WITH_BACKUP';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_ID_SUCCESS = 'SET_USER_ID_SUCCESS';
export const COUNTRIES = 'COUNTRIES';
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS';
export const DELETE_USERS = 'DELETE_USERS';
export const BIOMETRY_CHECK = 'BIOMETRY_CHECK';
export const UPDATE_CHECK_BIOMETRY_FLAG = 'UPDATE_CHECK_BIOMETRY_FLAG';
export const UPDATE_IS_BIOMETRY_GET_STARTED_ERROR =
    'UPDATE_IS_BIOMETRY_GET_STARTED_ERROR';
export const DISABLE_SELECT_PERSONA = 'DISABLE_SELECT_PERSONA';
export const USER_IS_UPDATED = 'USER_IS_UPDATED';
export const UPDATE_INITIAL_DEEPLINK = 'UPDATE_INITIAL_DEEPLINK';
export const GENERATE_TEMP_ISSUING_USER = 'GENERATE_TEMP_ISSUING_USER';
export const UPDATE_SHOW_SPLASH_SCREEN = 'UPDATE_SHOW_SPLASH_SCREEN';
export const INIT_BACKEND_ACCOUNT_IF_NOT_EXIST = 'CREATE_BACKEND_ACCOUNT';
export const INIT_BACKEND_ACCOUNT_SUCCESS = 'INIT_BACKEND_ACCOUNT_SUCCESS';
export const ADD_TERMS_AND_CONDITIONS_VERSION =
    'ADD_TERMS_AND_CONDITIONS_VERSION';
export const ADD_TERMS_AND_CONDITIONS_VERSION_SUCCESS =
    'ADD_TERMS_AND_CONDITIONS_VERSION_SUCCESS';
export const SAVE_LATEST_TERMS_AND_CONDITIONS_VERSION =
    'SAVE_LATEST_TERMS_AND_CONDITIONS_VERSION';
export const SET_DID_JWK = 'SET_DID_JWK';
export const DISABLE_BIOMETRY = 'DISABLE_BIOMETRY';
