export const VENDORS = 'VENDORS';
export const VENDORS_SUCCESS = 'VENDORS_SUCCESS';
export const OFFERS = 'OFFERS';
export const OFFERS_SUCCESS = 'OFFERS_SUCCESS';
export const VCLOFFERS_SUCCESS = 'VCLOFFERS_SUCCESS';
export const FINALIZE_OFFERS = 'FINALIZE_OFFERS';
export const FINALIZE_OFFERS_FROM_DIFF_ISSUERS =
    'FINALIZE_OFFERS_FROM_DIFF_ISSUERS';
export const SET_PROGRESS = 'SET_PROGRESS';
export const PUSH_OFFERS = 'PUSH_OFFERS';
export const PUSH_OFFERS_CLEAR = 'PUSH_OFFERS_CLEAR';
export const PUSH_OFFERS_SUCCESS = 'PUSH_OFFERS_SUCCESS';
export const SET_CREDENTIAL_MANIFEST = 'SET_CREDENTIAL_MANIFEST';
export const SET_HANDLED_OFFER_NOTIFICATION_ID =
    'SET_HANDLED_OFFER_NOTIFICATION_ID';
