export const CREDENTIAL_CATEGORIES = 'CREDENTIAL_CATEGORIES';
export const CREDENTIAL_CATEGORIES_SUCCESS = 'CREDENTIAL_CATEGORIES_SUCCESS';

export const SDK_INITIALIZED = 'SDK_INITIALIZED';

export const GET_ORGANIZATION_PROFILE_INFO = 'GET_ORGANIZATION_PROFILE_INFO';
export const GET_ORGANIZATION_PROFILE_INFO_SUCCESS =
    'GET_ORGANIZATION_PROFILE_INFO_SUCCESS';
export const SET_ISSUING_SEQUENCE = 'SET_ISSUING_SEQUENCE';
export const CLEAR_ISSUING_SEQUENCE = 'CLEAR_ISSUING_SEQUENCE';
export const JUMP_NEXT_ISSUING_SEQUENCE = 'JUMP_NEXT_ISSUING_SEQUENCE';
