export const DISCLOSURES = 'DISCLOSURES';
export const DISCLOSURES_SUCCESS = 'DISCLOSURES_SUCCESS';
export const SET_NO_DISCLOSURES_POPUP = 'SET_NO_DISCLOSURES_POPUP';
export const GET_DISCLOSURE_DATA = 'GET_DISCLOSURE_DATA';
export const SET_DISCLOSURE_DATA = 'SET_DISCLOSURE_DATA';
export const SET_DISCLOSURE_DATA_VERIFIED = 'SET_DISCLOSURE_DATA_VERIFIED';
export const CLEAR_DISCLOSURE_DATA = 'CLEAR_DISCLOSURE_DATA';
export const SAVE_ORIGINAL_ISSUING_SESSION = 'SAVE_ORIGINAL_ISSUING_SESSION';
export const CLEAR_ORIGINAL_ISSUING_SESSION = 'CLEAR_ORIGINAL_ISSUING_SESSION';
export const SET_IS_TEMP_USER_FIRST_ISSUING_SESSION =
    'SET_IS_TEMP_USER_FIRST_ISSUING_SESSION';
export const SET_SELECTED_CREDENTIALS = 'SET_SELECTED_CREDENTIALS';
export const SAVE_ORIGINAL_INSPECTION_SESSION =
    'SAVE_ORIGINAL_INSPECTION_SESSION';
export const CLEAR_ORIGINAL_INSPECTION_SESSION =
    'CLEAR_ORIGINAL_INSPECTION_SESSION';
