export const GET_CREDENTIALS = 'GET_CREDENTIALS';
export const VERIFIABLE_CREDENTIALS_SUCCESS = 'VERIFIABLE_CREDENTIALS_SUCCESS';
export const SAVE_SELF_REPORTED = 'SAVE_SELF_REPORTED';
export const UPDATE_CREDENTIAL_SUCCESS = 'UPDATE_CREDENTIAL_SUCCESS';
export const UPDATE_CREDENTIALS_SUCCESS = 'UPDATE_CREDENTIALS_SUCCESS';
export const UPDATE_CREDENTIAL = 'UPDATE_CREDENTIAL';
export const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';
export const SELF_REPORTED_CREDENTIALS_SUCCESS =
    'SELF_REPORTED_CREDENTIALS_SUCCESS';
export const UPDATE_IS_SELF_REPORT_IS_LOADING =
    'UPDATE_IS_SELF_REPORT_IS_LOADING';
export const UPDATE_IS_VF_CREDENTIALS_IS_LOADING =
    'UPDATE_IS_VF_CREDENTIALS_IS_LOADING';
export const DELETE_CREDENTIAL_BY_ID = 'DELETE_CREDENTIAL_BY_ID';
export const DELETE_CREDENTIAL_BY_ID_SUCCESS =
    'DELETE_CREDENTIAL_BY_ID_SUCCESS';
export const DELETE_CREDENTIALS = 'DELETE_CREDENTIALS';
export const DELETE_CREDENTIALS_SUCCESS = 'DELETE_CREDENTIALS_SUCCESS';
export const RESET_DATA = 'RESET_DATA';
export const RESET_DATA_SUCCESS = 'RESET_DATA_SUCCESS';
export const GET_SETTINGS = 'GET_SETTINGS';
export const SET_SETTINGS = 'SET_SETTINGS';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const DELETE_REVOKED_CREDENTIALS = 'DELETE_REVOKED_CREDENTIALS';
export const SET_PHONE_VERIFICATION_POPUP_CLOSED =
    'SET_PHONE_VERIFICATION_POPUP_CLOSED';
export const SET_SHOW_DISCLOSURE_TUTORIAL = 'SET_SHOW_DISCLOSURE_TUTORIAL';
