export const PUSH_REGISTER_DEVICE = 'PUSH_REGISTER_DEVICE';
export const PUSH_REMOVE_DEVICE = 'PUSH_REMOVE_DEVICE';
export const PUSH_UPDATE_DEVICE_TOKEN = 'PUSH_UPDATE_DEVICE_TOKEN';
export const GET_PUSHES = 'GET_PUSHES';
export const INCREMENT_DISCLOSURE_NOTIFICATIONS_COUNTER =
    'INCREMENT_DISCLOSURE_NOTIFICATIONS_COUNTER';
export const UPDATE_DISCLOSURE_NOTIFICATIONS_BADGE =
    'UPDATE_DISCLOSURE_NOTIFICATIONS_BADGE';
