export const GET_CREDENTIAL_TYPES_AND_SCHEMAS =
    'GET_CREDENTIAL_TYPES_AND_SCHEMAS';
export const GET_CREDENTIAL_TYPES_SUCCESS = 'GET_CREDENTIAL_TYPES_SUCCESS';
export const GET_UI_FORM_SCHEMA = 'GET_UI_FORM_SCHEMA';
export const GET_UI_FORM_SCHEMA_SUCCESS = 'GET_UI_FORM_SCHEMA_SUCCESS';
export const GET_CREDENTIAL_TYPES_SCHEMAS_SUCCESS =
    'GET_CREDENTIAL_TYPES_SCHEMAS_SUCCESS';
export const GET_PRESENTATION_SCHEMA = 'GET_PRESENTATION_SCHEMA';
export const GET_PRESENTATION_SCHEMA_SUCCESS =
    'GET_PRESENTATION_SCHEMA_SUCCESS';
