export const CredentialObject = {
    name: 'CredentialObject',
    primaryKey: 'id',
    properties: {
        type: 'string[]',
        id: 'string?',
        logo: 'string?',
        vendorCountry: 'string?',
        note: 'string?',
        issuer: 'Issuer?',
        credentialSchema: 'CredentialSchema?',
        credentialSubject: 'string?',
        offerId: 'string?',
        userId: 'string',
        issuanceDate: 'string?',
        isNewWaiting: 'bool?',
        withoutAccept: 'bool?',
        offerExpirationDate: 'string?',
        saveOfferDate: 'string?',
        vendor: 'Issuer?',
        hash: 'string?',
        status: 'string?',
        revocationDate: 'string?',
        revocationReason: 'string?',
        additionalInfo: 'CredentialAdditionalInfo?',
        isNewRevoked: 'bool?',
        linkCodeCommitment: 'LinkCodeCommitment?',
        credentialManifest: 'CredentialManifest?',
        vclToken: 'VCLToken?',
        default: 'bool?',
        jwt: 'string?',
        output_descriptors: 'string?',
        replacerId: 'string?',
        relatedResource: 'RelatedResource[]',
        dynamicRootProperties: 'string?',
    }
};
